CREATE TABLE IF NOT EXISTS weather_observations (
    StationId TEXT PRIMARY KEY,
    StationName TEXT,
    County TEXT,
    Township TEXT,
    CountyCode TEXT,
    TownCode TEXT,
    StationAltitude REAL,
    Latitude REAL,
    Longitude REAL,
    ObsTime DATETIME,
    Weather TEXT,
    VisibilityDescription TEXT,
    SunshineDuration REAL,
    Precipitation REAL,
    WindDirection REAL,
    WindSpeed REAL,
    Temperature REAL,
    Humidity REAL,
    AirPressure REAL,
    UVIndex TEXT,
    Max10MinAverage_WindSpeed REAL,
    Max10MinAverage_WindDirection REAL,
    Max10MinAverage_DateTime DATETIME,
    GustInfo_PeakGustSpeed REAL,
    GustInfo_WindDirection REAL,
    GustInfo_DateTime DATETIME,
    DailyHigh_AirTemperature REAL,
    DailyHigh_DateTime DATETIME,
    DailyLow_AirTemperature REAL,
    DailyLow_DateTime DATETIME,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
